<!DOCTYPE html>
<ht lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Culture</title>
    
    <?php
include "inc/baniereView.php";
include "inc/menuView.php"
    ?>

<div class="titre">
<h1>Culture</h1>

<div>
    <img src="img/culture.jpg" alt="photoCulture">
</div>

<div class="text">
    <h2>Divertissements</h2>
    <p>Au sein de la cité de Westminster, le quartier de West End regroupe un grand nombre d'attractions autour de Leicester Square, où de nombreux films sont joués en avant-première britannique et mondiale, et Piccadilly Circus et ses publicités électroniques couvrant de nombreux bâtiments.
    </p><br>
    <p>Dans cette zone se trouvent également le quartier des théâtres de Londres qui regroupe de nombreux cinémas, bars, pubs, boîtes de nuit, restaurants ainsi que le quartier chinois de Londres. Le Royal Ballet du Royaume-Uni, l’English National Ballet, le Royal Opera et l’English National Opera basés à Londres se produisent au Royal Opera House,au London Coliseum,au Sadler’s Wells Theatre et au Royal Albert Hall. Un peu plus à l'est se trouve Covent Garden. Shoreditch et Hoxton, situés à Hackney dans l'East End regroupent également de nombreux bars, restaurants, night-clubs et galeries. Upper Street, une rue de 2 km de long du district d'Islington, compterait plus de bars que n'importe quelle autre rue au Royaume-Uni. C'est également la première rue à proposer un accès internet sans fil dans ses cafés.
    </p><br>
    <p>Oxford Street, souvent citée comme étant la plus longue rue commerçante au monde, regroupe plus de 300 commerces sur environ 2 km, depuis Marble Arch, et accueille près de 200 millions de clients par an147. Bond Street à Mayfair abrite de nombreuses boutiques de luxe, de même que le quartier de Knightsbridge où se situe Harrods. Les quartiers de Knightsbridge (Sloane Street), Mayfair (Bond Street, Brook Street) et Chelsea (King's Road) regroupent de nombreux créateurs et boutiques de mode dont Vivienne Westwood, John Galliano, Stella McCartney, Manolo Blahnik et Jimmy Choo. Londres abrite également de nombreux marchés, dont Camden market pour la mode, Portobello Road pour les antiquités et Borough Market pour les produits bios.
    </p><br>
    <h2>Mode</h2>
    <p>Londres fait partie des 4 capitales de la mode, aux côtés de Paris, Milan et New York. La Fashion Week de Londres qui a lieu depuis 1984 compte parmi les plus importantes semaines de la mode du monde. Londres est connue pour son rôle mélangeant créativité débridée et conservatisme, sa mode de rue, ainsi que sa mode masculine traditionnelle symbolisée par Savile Row (tailleurs) et Jermyn Street (chemises, chaussures). Dans les années 1960, c'est le Swinging London : Londres compte alors près de deux mille magasins de vêtements, et Carnaby Street en est l'épicentre, mais aussi King's Road à Chelsea. A la fin des années 1970, c'est la mode punk, notamment représentée par Vivienne Westwood, qui remet Londres sur le devant de la scène. Au début du XXIè siècle des créateurs comme John Galliano, Alexander Mc Queen, Stella McCartney ou Jimmy Choo témoignent du dynamisme de la ville. Le Central Saint Martins College of Art and Design est une des plus prestigieuses écoles de mode et de stylisme au monde. La ville occupe ainsi une place éminente sur la scène mondiale dans les secteurs liés au luxe. En 2017 Londres s'est classée deuxième ville dans le monde, après Paris, pour le nombre d'ouvertures dans le secteur du luxe et des produits premium.
    </p><br>
    <h2>Arts</h2>
    <p>Londres abrite également de nombreuses écoles des arts du spectacle comme la Central School of Speech and Drama, d'où sont sortis Judi Dench et Laurence Olivier, la London Academy of Music and Dramatic Art, où ont été formés Jim Broadbent et Donald Sutherland entre autres, ainsi que la Royal Academy of Dramatic Art, qui compte Joan Collins et Roger Moore parmi ses anciens élèves. Le Festival du film de Londres, organisé par le British Film Institute, se tient dans la ville tous les ans en octobre.
    </p><br>
    <h2>Musées</h2>
    <p>Londres possède un panel de musées parmi les plus importants au monde. On en compte 240 (contre 173 à Paris), musées, galeries et autres institutions, dont beaucoup sont gratuits et sont des attractions touristiques majeures et jouent un rôle de recherche. Le premier d'entre eux à avoir été créé était le British Museum de Bloomsbury, en 1753. Contenant à l'origine des antiquités, des spécimens d'histoire naturelle et la bibliothèque nationale, le musée est l'un des musées les plus grands et les plus célèbres au monde, et compte maintenant sept millions d'artefacts provenant du monde entier. En 1824, la National Gallery a été fondée pour abriter la collection nationale britannique de peintures occidentales. Dans la seconde moitié du XIXe siècle, la localité de South Kensington a été développée comme " Albertopolis ", un quartier culturel et scientifique. Trois grands musées nationaux s'y trouvent: le Victoria and Albert Museum, plus grand musée d'arts appliqués du monde, le musée d'histoire naturelle et ses 70 millions de specimen, et le Science Museum. La National Portrait Gallery a été fondée en 1856 pour abriter des représentations de personnages de l'histoire britannique ; ses collections comprennent désormais la plus vaste collection de portraits au monde. La galerie nationale d'art britannique est à la Tate Britain, créée à l'origine comme une annexe de la National Gallery en 1897. La Tate Gallery, comme on l'appelait auparavant, est également devenue un centre majeur de l'art moderne ; en 2000, cette collection a déménagé à la Tate Modern, une nouvelle galerie installée dans l'ancienne centrale électrique de Bankside, construit par les deux architectes bâlois Pierre Herzog et Jacques de Meuron. On peut également citer le National Maritime Museum de Greenwich, le plus grand de son genre au monde, la Wallace Collection, une des plus belles collections privées d'art au monde, ou le célèbre Madame Tussauds. Le Musée impérial de la guerre est l'un des musées de guerre les plus importants au monde.
    </p><br>
    <p>La British Library est l'une des plus grandes bibliothèques du monde et la bibliothèque nationale du Royaume-Uni. Il existe de nombreuses autres bibliothèques de recherche, dont la Wellcome Library et le Dana Center, ainsi que des bibliothèques universitaires, notamment la British Library of Political and Economic Science à LSE, la Central Library à Imperial, la Maughan Library à King's et la Bibliothèque de Senate House à l'Université de Londres.
    </p><br>
    <h2>Musique</h2>
    <p>Londres est une des capitales mondiales de la musique classique et pop/rock. La ville abrite le siège d'une des quatre grands majors du disque, EMI Group, ainsi que d'innombrables musiciens, groupes, orchestres et professionnels de la musique.
    </p><br>
    <p>Cinq orchestres professionnels sont basés à Londres : l'Orchestre symphonique de Londres, l'Orchestre philharmonique de Londres, l'Orchestre philharmonique royal, l'Orchestre Philharmonia et l'Orchestre symphonique de la BBC. De nombreux autres orchestres sont également situés dans la ville : l'Orchestre de l'âge des Lumières, le London Sinfonietta et les ensembles London Mozart Players et English Chamber Orchestra. Le point culminant de la saison classique se produit tous les ans en été avec The Proms, une série d'environ 70 concerts de musique classique au Royal Albert Hall.
    </p><br>
    <p>Londres possède deux principaux opéras : le Royal Opera House et le Coliseum Theatre. Les ballets Royal Ballet et l'English National Ballet se produisent au Royal Opera House, au Sadler's Wells Theatre et au Royal Albert Hall.
    </p><br>
    <p>Londres abrite de nombreuses salles de concerts pop/rock telles Earls Court et Wembley Arena, la Carling Brixton Academy ou l'Hammersmith Apollo, et d'innombrables salles plus intimistes. De nombreux artistes résidents à Londres et dans les Home Counties environnants. La ville a vu s'ouvrir le tout premier Hard Rock Cafe ainsi que les célèbres studios Abbey Road. Dans les années 1960, 1970 et 1980, musiciens et groupes comme Elton John, Pink Floyd, Cliff Richard, David Bowie, Queen, The Kinks, The Rolling Stones, The Who, Eric Clapton, Led Zeppelin, The Small Faces, Iron Maiden, Fleetwood Mac, Elvis Costello, Cat Stevens, The Police, The Cure, Madness, The Jam, Ultravox, Dire Straits, Spandau Ballet, Culture Club, Dusty Springfield, Phil Collins, Rod Stewart, Adam Ant, Status Quo et Sade chantent les rythmes de Londres.
    </p><br>
    <p>Londres a joué un rôle déterminant dans le développement de la musique punk, avec des figures telles que les Sex Pistols, The Clash, et Vivienne Westwood tous basés dans la ville. Les artistes les plus récents à émerger de la scène musicale londonienne comprennent George Michael et Wham!, Kate Bush, Seal, les Pet Shop Boys, Bananarama, Siouxsie and the Banshees, Bush, les Spice Girls, Jamiroquai, Blur, McFly, The Prodigy, Gorillaz, Bloc Party, Mumford & Sons, Coldplay, Amy Winehouse, Adele, Sam Smith, Ed Sheeran, Paloma Faith, Ellie Goulding, One Direction et Florence and the Machine.
    </p><br>
    <p>En tant que principale agglomération du Royaume-Uni, Londres a joué un rôle majeur dans la naissance des différents courants de musiques urbaines, punk et électroniques,[réf. nécessaire] tels que le drum and bass, garage, grime et dubstep. De nombreux artistes de hip-hop britannique habitent également à Londres.
    </p><br>
    <p>En 2006, DJ Magazine a publié une enquête réalisée auprès de 600 DJ internationaux qui a établi que Londres abritait trois des meilleurs night-clubs au monde : le Fabric, The End et le Turnmills. En 2007, lors d'un nouveau sondage, le Fabric a été classé en deuxième position et The End en quatrième position ; six clubs londoniens se trouvent dans les cinquante premières places.
    </p><br>
    <h2>Cinéma et télévision</h2>
    <p>Londres joue un rôle important dans l'industrie cinématographique. Quatre grands studios sont situés dans la ville : Pinewood, Ealing, Shepperton, Elstree, ainsi que Leavesden. De nombreuses entreprises spécialisées dans la postproduction et les effets spéciaux, comme Working Title Films ont leur siège à Londres. De nombreux films ont pour cadre la ville et ont été tournés à Londres même : Oliver Twist (1948), Scrooge (1951), Peter Pan (1953), Les 101 Dalmatiens (1961), My Fair Lady (1964), Mary Poppins (1964), Blow Up (1966), Orange Mécanique (1971), Du sang sur la Tamise (1980), Coup de foudre à Notting Hill (1999), 28 jours plus tard (2002), Love Actually (2003), V for Vendetta (2005), Match Point (2005), The Queen (2006) ou Le Discours d'un Roi (2010). Ce sont aussi et surtout les célèbres sagas Harry Potter (qui s'est déroulée entre autres à Londres gare de King's Cross par exemple) et James Bond (comme dans Skyfall en 2012). Les acteurs et cinéastes londoniens célèbres comprennent Charlie Chaplin, Alfred Hitchcock, Michael Caine, Helen Mirren, Gary Oldman, Christopher Nolan, Hugh Grant, Jude Law, Benedict Cumberbatch, Tom Hardy, Keira Knightley et Daniel Day-Lewis. La National Film and Television School créée en 1971 est une des plus prestigieuses écoles de cinéma du monde. Depuis 2008, les British Academy Film Awards ont eu lieu au Royal Opera House. Londres est un centre majeur pour la production télévisuelle, avec des studios dont le BBC Television Centre, The Fountain Studios et The London Studios.
    </p><br>
    <h2>Manifestations culturelles</h2>
    <p>Tout au long de l'année il y a de très nombreux événements, à commencer par le défilé du nouvel an (relativement récent), un feu d'artifice au London Eye ; La deuxième plus grande fête de rue au monde, le carnaval de Notting Hill, a lieu chaque année à la fin août. Les défilés traditionnels incluent le Lord Mayor's Show (Procession du Lord Maire) de novembre, un événement séculaire célébrant la nomination annuelle d'un nouveau Lord-maire de la City de Londres avec une procession dans les rues de la ville, et Trooping the Colour, un spectacle militaire officiel organisé par les régiments du Commonwealth et britanniques pour célébrer l'anniversaire officiel de la Reine. Le Boishakhi Mela est un festival du nouvel an bengali célébré par la communauté bangladaise britannique. Il s'agit du plus grand festival asiatique en plein air d'Europe, et du deuxième plus grand festival de rue du Royaume-Uni, attirant plus de 80 000 visiteurs de tout le pays.
    </p><br>
    <h2>Londres dans la culture populaire</h2>
    <p>Les personnages de Sherlock Holmes, Jack l'Éventreur et d'Oliver Twist sont connus et rattachés à l'histoire culturelle de Londres.
    </p><br>
    <p>Londres a inspiré de nombreux auteurs et été le sujet de multiples œuvres de littérature. William Shakespeare a passé une grande partie de sa vie et a également travaillé à Londres. Son contemporain Ben Jonson a également vécu à Londres et certains de ses écrits, notamment L'Alchimiste, se déroulent dans la ville. Concernant ceux ayant écrit l'histoire de la ville, on peut citer Samuel Pepys (1633-1703), qui a notamment relaté de grands événements comme l'épidémie de peste de Londres et le grand incendie de 1666. Charles Dickens (1812-1870) est étroitement associés à la ville, dont la description d'un Londres embrumé, neigeux et crasseux aux rues remplies de balayeurs et pickpockets a eu une influence majeure sur la perception de la ville à l'époque victorienne.
    </p><br>
    <p>Life of Johnson (en), la biographie de James Boswell se déroule principalement à Londres et est à l'origine de la fameuse citation de Samuel Johnson : « Quand un homme en a assez de Londres, il en a assez de la vie car il y a à Londres tout ce que la vie peut apporter » (When a man is tired of London, he is tired of life; for there is in London all that life can afford)172. Le Journal de l'année de la peste (en) de Daniel Defoe est une œuvre de fiction basée sur la grande peste de 1665.
    </p><br>
    <p>À travers Phileas Fogg, héros du roman Le Tour du monde en quatre-vingts jours (paru en 1872), son auteur Jules Verne se plait à représenter l'archétype du gentleman anglais victorien, vu par les Français. Cet « homme-horloge », très stoïque, mène une vie réglée à la minute près, exerçant quotidiennement les mêmes activités, se résumant à celles pratiquées au Reform Club, club de gentlemen londonien. Le roman de 1933 de George Orwell Dans la dèche à Paris et à Londres décrit la vie des pauvres dans les deux capitales britannique et française. Peter Ackroyd est un écrivain moderne qui a également été influencé par la ville, notamment dans London: The Biography, The Lambs of London et Hawksmoor. Bloomsbury et le quartier d'Hampstead ont traditionnellement été au cœur du courant de littérature de Londres. Le poète Paul Verlaine s'y installa en 1875 durant deux ans et y séjourna à plusieurs reprises. Il évoque sa vie londonienne dans plusieurs de ses œuvres, telles que Un tour à Londres (1894), plusieurs de ses lettres (notamment à Edmond Lepelletier), ainsi que quelques dessins.
    </p><br>
    <p>Londres est une ville privilégiée dans les polars, où elle sert de décor de manière très récurrente. Un incontournable de ce genre est la série des aventures de Sherlock Holmes d'Arthur Conan Doyle, dépeignant la ville au xixe siècle et au début du xxe siècle. Un autre héros célèbre de la littérature policière britannique vit dans cette ville, le détective belge Hercule Poirot, créé par Agatha Christie et apparu en 1920.
    </p><br>
    <p>Londres inspira aussi beaucoup la littérature fantastique, comme l'illustre le roman de Robert Louis Stevenson L'Étrange Cas du docteur Jekyll et de M. Hyde (1886).
    </p><br>
    <h2>Peinture</h2>
    <p>Un des peintres anglais les plus célèbres, le romantique William Turner, représenta Londres dans plusieurs de ses œuvres, comme dans une série de Vues de Londres depuis Greenwich, ou bien L'Incendie de la Chambre des lords et des communes (1835). Quant à William Hogarth, il est à l'origine d'une série de six tableaux et gravures, réalisées entre 1731 et 1732 : La Carrière d'une prostituée.
    </p><br>
    <p>La capitale anglaise attira beaucoup les artistes européens (en particulier français) de la fin du xixe siècle, qui leur permettait de se dépayser sans aller loin ; ce fut principalement le cas des peintres. Un des meilleurs exemples est certainement Claude Monet, qui y séjourna plusieurs fois, y résida et y exposa. Dans ses œuvres, il confondit dans les mêmes brouillards impressionnistes les villes de Londres, de Venise ou la Normandie. Parmi ses œuvres londoniennes, on peut citer la série des Parlements de Londres (19 peintures du Parlement, conçues entre 1900 et 1905), celle des Charing Cross Bridge (série de 37 tableaux peints entre 1899 et 1904, représentant le Hungerford Bridge) et, plus généralement, des représentations de la Tamise. Toujours en matière de ponts, son compatriote Alfred Sisley peignit en 1874 Sous le pont de Hampton Court. James Tissot, lui, préféra représenter le portique de la National Gallery dans quelques-unes de ses œuvres. Dans les scènes historiques, Édouard Cibot représenta en 1835 Anne Boleyn à la Tour de Londres, où l'on voit Anne Boleyn (mère de la reine Élisabeth Ire), accusée d'intriguer, emprisonnée à la tour de Londres.
    </p><br>
    <p>Walter Sickert, postimpressionniste anglais d'origine allemande, était fasciné par l'affaire de Jack l'Éventreur. Il était convaincu de loger dans la même chambre que le criminel occupait avant son arrivée. C'est pour cela qu'il nomma cette pièce la Jack the Ripper's bedroom et qu'il représenta (vers 1907) sur une peinture de ce titre. Il fut lié à cette affaire, au point qu'il figure sur la liste des suspects ayant pu jouer le rôle de l'assassin ou de son complice.
    </p><br>
    <p>Le peintre et graveur américain James McNeill Whistler aussi figura la ville dans ses œuvres. Il immortalisa dans Nocturne en bleu et or - le Vieux Pont de Battersea (vers 1872-1875) l'ancien pont de Battersea, détruit en 1885 pour être remplacé l'année suivante par la version actuelle.
    </p><br>
</div>
</div>