<?php
include "inc/menuView.php"
?>

<div class="titre">
    <h1>Historique</h1>
    <div>
        <img src="img/histoire.jpg" alt="Histoire">
    </div>
    <div class="text">

    <p>Les régions aux alentours de Londres (aujourd'hui situées à l'intérieur des frontières du Grand Londres) semblent avoir été habitées par des Bretons insulaires depuis les temps préhistoriques, mais aucune trace archéologique n'a été mise au jour au nord du pont de Londres, lieu où la ville est véritablement née et d'où elle s'est développée. Les plus anciennes traces certaines d'installations durables remontent à l'an 43 et sont dues aux Romains qui, à la suite de leur conquête de la Bretagne, y bâtissent une première ville. Ce premier campement est appelé Londinium. Le pont de Londres se trouvait au centre du tout nouveau réseau de routes créé par les Romains et était un lieu de passage privilégié pour traverser la Tamise, ce qui a attiré de nombreux commerçants et ainsi contribué à la croissance de la ville. Londres est vite devenue un important centre d'échanges et de commerce, la Tamise permettant d'acheminer facilement des marchandises jusqu'au cœur de la ville.
    </p><br>
    <p>Seulement 18 ans après la fondation de la ville par les Romains, la reine Boadicée, à la tête du peuple celte des Iceni, se dresse contre l'invasion romaine et prend Londres pour cible. Le gouverneur Suetonius Paulinus, alors occupé à exterminer les druides sur l'île d'Anglesey, ne peut constituer à temps une armée pour contrer l'invasion celte. La ville est partiellement évacuée, mais des milliers de commerçants sont tués. Londres est alors totalement pillée et détruite. Des fouilles archéologiques ont permis de mettre au jour la présence de débris brûlés recouvrant des pièces et des poteries datant de 60, à l'intérieur des limites de la ville romaine.
    </p><br>
    <p>La ville est rapidement reconstruite et prospère de nouveau, à l'image du commerce en Bretagne, remplaçant Colchester en tant que capitale de la province romaine de Bretagne. Il n'existe cependant pas d'informations permettant de dater et d'expliquer le transfert de la capitale. Vers le iie siècle, la ville s'entoure de murailles : le mur de Londres. Pendant plus d'un millénaire, les frontières de la ville sont marquées par ce mur qui délimite une zone largement englobée aujourd'hui par celle de la City. À son apogée au iiie siècle, la population de Londinium atteint entre 45 000 et 60 000 personnes suivant les sources. Lorsque l'Empire romain commence à décliner, les troupes protégeant la ville sont rappelées sur le continent, Londres commence à péricliter et sa population diminue. Il existe peu d'informations sur cette période appelée Dark Ages of London (« Les âges sombres de Londres »), mais après le départ des Romains de Grande-Bretagne en 410, il est largement établi qu'au ve siècle, Londres est en ruine et pratiquement abandonnée.
    </p><br>

    <h2>L'occupation anglo-saxonne</h2>
    <p>La position privilégiée de la ville sur la Tamise en fait un lieu stratégique et vers l'an 600, les Anglo-Saxons fondent une nouvelle ville, Lundenwic, à environ 1 km en amont de la ville romaine, à l'endroit où se trouve aujourd'hui Covent Garden. Un port de pêche et de commerce est probablement localisé à l'embouchure de la rivière Fleet. Lundenwic prospère jusqu'en 851, lorsque la ville est envahie et complètement rasée par les Vikings. Après cette occupation viking, Alfred le Grand rétablit la paix et fait déplacer la ville dans les murailles de la vieille cité romaine (alors appelée Lundenburgh) en 886. La ville originale est devenue Ealdwic (« vieille ville »), dont le nom a survécu jusqu'à aujourd'hui pour donner Aldwych.
    </p><br>
    <p>Ensuite, sous le contrôle de plusieurs rois anglais, Londres connaît une nouvelle phase de prospérité, devenant un lieu de pouvoir ainsi qu'un centre d'échanges et de commerce. Cependant, les raids vikings reprennent au xe siècle et atteignent leur apogée en 1013, lorsque la ville fut assiégée par le Danois Knut le Grand et que le roi Æthelred le Malavisé est contraint de s'enfuir. Lors d'une contre-attaque, l'armée du roi Æthelred remporte une victoire en détruisant le pont de Londres alors que la garnison danoise se trouve dessus. Knut finit cependant par devenir roi d'Angleterre et ses descendants règnent jusqu'en 1042. Un roi saxon, Édouard le Confesseur, leur succède et refonde l'abbaye de Westminster ainsi que le palais de Westminster. À cette époque, Londres est devenu la cité la plus grande et la plus prospère d'Angleterre, bien que le siège du gouvernement se trouve toujours à Winchester.
    </p><br>

    <h2>Londres médiévale</h2>

    <p>Après la bataille d'Hastings, le duc de Normandie Guillaume le Conquérant est couronné roi d'Angleterre dans la toute nouvelle abbaye de Westminster, le jour de Noël 1066. Il accorde certains privilèges aux habitants de Londres tout en construisant, dès la fin 1066, un château en terre et en bois au sud-est de la ville derrière les remparts pour maintenir le contrôle sur la population et se mettre à l'abri en cas d'émeute. À la place de ce réduit castral, Guillaume, bâtira plus tard un énorme donjon : la tour Blanche (en anglais : White Tower). Ce château, agrandi par les rois suivants, sert de résidence royale puis de prison et est aujourd'hui connu sous le nom de tour de Londres.
</p><br>
    <p>En 1097, Guillaume le Roux commence la construction du hall de Westminster, près de l'abbaye du même nom. Ce hall est à l'origine du palais de Westminster, la résidence royale tout au long du Moyen Âge. Westminster devient le siège de la cour royale et du gouvernement, tandis que la Cité de Londres voisine forme un centre d'échanges et de commerce prospère sous l'autorité de sa propre administration, la Corporation of London. Les villes aux alentours se développent et forment la base du cœur de Londres moderne, remplaçant Winchester en tant que capitale du royaume d'Angleterre au xiie siècle.
    </p><br>
    <p>Le 2 juin 1216, le prince Louis (futur Louis VIII) s'empare de la ville qu'il conservera jusqu'en 1217.
    </p><br>

    <h2>Londres aux temps modernes</h2>

    <p>Après la défaite de l'Invincible Armada espagnole en 1588, une certaine stabilité politique en Angleterre permet à Londres de se développer davantage. En 1603, Jacques VI d'Écosse monte sur le trône d'Angleterre et s'efforce d'unifier les deux pays. Ses lois anticatholiques le rendent très impopulaire et il est victime d'une tentative d'assassinat le 6 novembre 1605, la fameuse conspiration des poudres.
    </p><br>
    <p>Plusieurs épidémies de peste noire touchent Londres au début du xviie siècle, culminant avec la grande peste de Londres de 1665, qui tue environ 20 % de la population. L'année suivante, le grand incendie de 1666 détruit une grande partie des maisons en bois de la ville. La reconstruction de Londres occupe toute la décennie suivante.
    </p><br>

    <h2>L'époque contemporaine</h2>

    <p>De 1825 à 1925, Londres est la ville la plus peuplée au monde. Cette croissance est accélérée par la construction des premières lignes de chemin de fer à Londres, rapprochant considérablement les villes avoisinantes. Porté par un essor boursier exceptionnellement rapide, ce réseau ferroviaire s'étend rapidement et permet à ces villes de croître tout en permettant à Londres de s'étendre et d'englober les villages aux alentours, à l'image de Kensington. L'apparition des premiers embouteillages en centre-ville mène à la création, en 1863, du premier système de transport souterrain au monde, le métro de Londres, accélérant encore le développement de l'urbanisation. Grâce à cette croissance rapide, Londres devient l'une des premières villes à dépasser le million d'habitants et la première à dépasser les cinq millions.
    </p><br>
    <p>Le gouvernement local de Londres éprouve des difficultés à gérer l'expansion rapide de la ville, surtout au niveau des infrastructures. Entre 1855 et 1889, le Metropolitan Board of Works supervise la croissance des infrastructures. Il est remplacé par le comté de Londres, géré par le London County Council, la première assemblée élue au niveau de la ville, jusqu'en 1965.
    </p><br>
    <p>Le Blitz et les bombardements allemands de la Luftwaffe durant la Seconde Guerre mondiale entraînent la mort d'environ 30 000 personnes et la destruction de nombreuses habitations et bâtiments dans la ville. La reconstruction dans les années 1950, 1960 et 1970 se caractérise par une absence d'unité architecturale, typique du Londres moderne. En 1965, les limites de Londres sont modifiées pour tenir compte de l'expansion de la ville en dehors du comté de Londres. Le nouveau territoire agrandi, administré par le Greater London Council, prend le nom de Grand Londres.
    </p><br>
    <p>Dans les décennies qui suivent la Seconde Guerre mondiale, une large immigration provenant des pays du Commonwealth décolonisés fait de Londres une des villes européennes les plus ethniquement cosmopolites. L'intégration des nouveaux immigrants ne se fait pas toujours en douceur, avec par exemple les émeutes de Brixton dans les années 1980, mais elle se déroule mieux que dans d'autres régions britanniques. Après l'abolition du Greater London Council en 1987, Londres est privé d'une administration centrale jusqu'à la création, en 2000, de la Greater London Authority et du poste du Maire de Londres (Mayor of London).
    </p><br>
    <p>Le renouveau économique des années 1980 rétablit Londres sur le devant de la scène internationale. En 2012, Londres devient la première ville à accueillir les Jeux olympiques modernes pour la troisième fois, tandis qu'en 2015 la population municipale dépasse 8,63 millions d'habitants, son plus haut niveau depuis 1939. En 2016, Londres est la première capitale occidentale à élire un maire musulman, le travailliste Sadiq Khan.
    </p><br>
    <p>En tant que siège du gouvernement et principale agglomération du Royaume-Uni, la ville connaît de nombreux épisodes terroristes. L'IRA provisoire tente de mettre le gouvernement britannique sous pression au sujet des négociations en Irlande du Nord, interrompant fréquemment les activités de la ville avec des alertes à la bombe ou des attentats jusqu'au cessez-le-feu de 1997. Le 7 juillet 2005, une série d'attentats est perpétrée dans les transports en commun londoniens par des kamikazes islamistes, 24 heures seulement après que l'organisation des Jeux olympiques de 2012 est confiée à la ville. Le 22 mars 2017, un attentat revendiqué par l'État islamique est commis par Khalid Masood sur le pont de Westminster et dans l'enceinte du Parlement ; il fait 3 morts (4 si on compte le terroriste) et une cinquantaine de blessés63,64. La Police métropolitaine a précisé que Masood ne faisait pas partie d'une organisation terroriste et qu'il a agi seul65. Trois mois plus tard, une autre attaque terroriste touche le centre de la ville, faisant huit morts.
    </p><br>